version: 0.0
os: linux
files:
  - source: muldum-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/app

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
