services:
  postgres:
    image: 'postgres:latest'
    container_name: muldum-postgres
    environment:
      - POSTGRES_DB=muldum
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '5432:5432'
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: muldum-app-v2
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/muldum
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - app-network
networks:
  app-network:
