services:
  postgres:
    image: 'postgres:latest'
    container_name: muldum-postgres
    environment:
      - POSTGRES_DB=muldum
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '5432:5432'
    networks:
      - app-network
  redis:
    image: 'redis'
    container_name: muldum-redis
    ports:
      - '6379:6379'
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: muldum-app-v2
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - GOOGLE_SHEETS_KEY_FILE_PATH={GOOGLE_SHEETS_KEY_FILE_PATH}
    networks:
      - app-network
networks:
  app-network:
